import "./parse-params.test.js";
import "./url-allowlist.test.js";
import "./image-logger.test.js";
import "./fetch-image.test.js";
import "./process-image.test.js";
import "./api-image.test.js";
import "./system.test.js";
import "./sharp-smoke.test.js";
import "./static-pages.test.js";
